version: "3.8"
services:
  jupyter:
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile-mac
    container_name: jupyter-cpu-deep-learning
    ports:
      - "8888:8888"
    volumes:
      - ./:/workfiles
