# Use TensorFlow CPU-based Jupyter image
FROM tensorflow/tensorflow:latest-jupyter

# Install additional Python libraries
RUN pip install --no-cache-dir scikit-learn pandas matplotlib seaborn torch

# Set working directory
WORKDIR /workfiles

# Expose Jupyter Notebook?
#EXPOSE 8888